name: Publish

on:
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: macos-latest
            target: arm64
          - runner: macos-latest
            target: x64
          - runner: ubuntu-latest
            target: arm64
          - runner: ubuntu-latest
            target: x64
          - runner: windows-latest
            target: x64
    name: Build on ${{ matrix.platform.runner }} for ${{ matrix.platform.target }}
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps
        with:
          gh-token: ${{ secrets.GH_TOKEN }}

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm build

      - name: Test Binding
        run: pnpm test:release-binding

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: bindings-${{ matrix.platform.target }}
          path: |
            build/Release/rocksdb-js.node
          if-no-files-found: error

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps
        with:
          gh-token: ${{ secrets.GH_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: bindings-${{ matrix.platform.target }}
          path: prebuilds

      - name: List artifacts
        run: ls -la prebuilds

      - name: Get package.json info
        id: get-package-info
        run: |
          echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT
          echo "homepage=$(node -p "require('./package.json').homepage")" >> $GITHUB_OUTPUT
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      # TODO:
      #  - Move artifacts to separate packages
      #  - Write `package.json` for each package
      #    - Set name @harperdb/rocksdb-js-<platform>-<arch>
      #    - Set version to ${{ steps.get-package-info.outputs.version }}
      #  - Publish packages
      # @harperdb/rocksdb-js-macos-arm64
      # @harperdb/rocksdb-js-macos-x64
      # @harperdb/rocksdb-js-linux-arm64
      # @harperdb/rocksdb-js-linux-x64
      # @harperdb/rocksdb-js-windows-arm64
      # @harperdb/rocksdb-js-windows-x64

      - name: Publish rocksdb-js to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --tag ${{ github.event.release.prerelease && 'next' || 'latest' }}

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "text": "Published ${{ steps.get-package-info.outputs.name }}@${{ steps.get-package-info.outputs.version }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Published ${{ steps.get-package-info.outputs.name }}@${{ steps.get-package-info.outputs.version }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "https://github.com/HarperFast/rocksdb-prebuilds/releases/tag/v${{ needs.check.outputs.version }}"
                  }
                }
              ]
            }
