name: Publish

on:
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preflight:
    name: Preflight
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps
        with:
          gh-token: ${{ secrets.GH_TOKEN }}

      - name: Check versions
        shell: bash
        run: node scripts/check-versions.mjs

      - name: Build
        shell: bash
        run: pnpm build

      - name: Test
        shell: bash
        run: pnpm test

  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: macos-latest
            name: darwin-arm64
            target: arm64
          - runner: macos-latest
            name: darwin-x64
            target: x64
          - runner: ubuntu-24.04-arm
            name: linux-arm64
            target: arm64
          - runner: ubuntu-22.04
            name: linux-x64
            target: x64
          - runner: windows-11-arm
            name: win32-arm64
            target: arm64
          - runner: windows-latest
            name: win32-x64
            target: x64
    name: Build on ${{ matrix.platform.runner }} for ${{ matrix.platform.name }} (${{ matrix.platform.target }})
    runs-on: ${{ matrix.platform.runner }}
    needs: preflight
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps
        with:
          gh-token: ${{ secrets.GH_TOKEN }}

      - name: Build binding
        shell: bash
        run: pnpm build

      - name: Test binding
        shell: bash
        run: node scripts/test-binding.mjs

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.platform.name }}
          path: |
            build/Release/rocksdb-js.node
          if-no-files-found: error

  publish:
    name: Publish packages
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps
        with:
          gh-token: ${{ secrets.GH_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          path: artifacts

      - name: List artifacts
        shell: bash
        run: find artifacts -ls

      - name: Get package.json info
        id: get-package-info
        shell: bash
        run: |
          echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT
          echo "homepage=$(node -p "require('./package.json').homepage")" >> $GITHUB_OUTPUT
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Publish bindings to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          TAG: ${{ github.event.release.prerelease && 'next' || 'latest' }}
        shell: bash
        run: node scripts/publish-bindings.mjs

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        shell: bash
        run: pnpm publish --access public --no-git-checks --tag ${{ github.event.release.prerelease && 'next' || 'latest' }}

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "text": "Published ${{ steps.get-package-info.outputs.name }}@${{ steps.get-package-info.outputs.version }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Published ${{ steps.get-package-info.outputs.name }}@${{ steps.get-package-info.outputs.version }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "https://github.com/HarperFast/rocksdb-prebuilds/releases/tag/v${{ steps.get-package-info.outputs.version }}"
                  }
                }
              ]
            }
